### ISSUE TITLE
Reference fields fetched but not displayed

### ISSUE THREAD

**Issue by kix** [marmelab/admin-on-rest#425]
I'm using `admin-on-rest` `0.9.0`
I have a listing defined like this:
```jsx
export const LessonList = (props) => (
    <List {...props} filters={<LessonFilter/>}>
        <Datagrid>
            <TextField source="id" />
            <TextField source="title" />
            <ReferenceField label="Language" source="language_id" reference="languages">
                <TextField source="name" />
            </ReferenceField>
            <EditButton basePath="/lessons" />
        </Datagrid>
    </List>
);
```
When the listing is displayed, I see a bunch of GET requests for matching languages, all of those have the data (and the name is there) and are `200 OK`. However, instead of values in the grid I see only preloaders. In the console I see this:
```
utils.js:215 handleFetch has been cancelled 
utils.js:215 fetchReference has been cancelled 
utils.js:215 fetchReference has been cancelled 
utils.js:215 fetchReference has been cancelled 
utils.js:215 fetchReference has been cancelled 
utils.js:215 fetchReference has been cancelled 
utils.js:215 fetchReference has been cancelled 
utils.js:215 fetchReference has been cancelled 
```
However, after I open `/languages` and switch back to `/lessons`, the values that were fetched for the languages listing are displayed in the lessons listing now, too. Same happens after opening a language editor (which has a select for all the language values).

**Comment by wadjeroudi** [comment]
I think you're using jsonServer for your REST, and it should be fixed in 0.9.1.

**Comment by fzaninotto** [comment]
Can you confirm v0.9.1 fixes your bug?

**Comment by kix** [comment]
@fzaninotto, it does; thanks!

**Comment by kodepareek** [comment]
Hello all. 

I am getting the ReferenceField displayed however the console is still showing this error. I am on version 0.9.3

```

fetchReference has been cancelled 
utils.js:215 fetchReference has been cancelled 
utils.js:215 fetchReference has been cancelled 
utils.js:215 fetchReference has been cancelled 
utils.js:215 fetchReference has been cancelled 
utils.js:215 fetchReference has been cancelled 
utils.js:215 fetchReference has been cancelled 
```



following is the component that is displaying when this error is shown 

```
export const EditorView = (props) => {
  return (
    <List {...props} title="Fresh Tales" sort={{ field:'ID', order: 'ASC'}} filters={<EditorFilter />}>
      <Datagrid>
        <TextField source="id" />
        <TextField source="format" />
        <TextField source="text" />
        <ReferenceField label="Writer" source="writerId" reference="writers">
          <TextField source="name" />
        </ReferenceField>
        <TextField source="stars" />
        <EditButton />
        <ApproveButton />
        <RejectButton />
      </Datagrid>
    </List>
  )
}

```

**Comment by fzaninotto** [comment]
This is not an error, but a normal log by redux saga. It should disappear if you compile your code with `ENV=production`.

**Comment by kodepareek** [comment]
Aah got it. Thanks.
